export const characters = {
    'Akuma': ['Akuma', 'Rockstar Akuma', 'Thunder God Akuma', 'Captain Akuma', 'High Elf Akuma'],
    'Angel': ['Angel', 'Blossom Angel', 'Voidborn Angel', 'Neon Core Angel', 'Forest Goddess Angel'],
    'Astaroth': ['Stonebreaker Astaroth', 'Forest Behemoth Astaroth', 'Forest Behemoth Astaroth Gilded', 'Forest Behemoth Astaroth Opulent', 'Forest Behemoth Astaroth Rosy', 'Forest Behemoth Astaroth Ashen', 'Astaroth', 'Arctic Monster Astaroth', 'Royal Guard Astaroth', 'Sand Soldier Astaroth', 'Infernal Astaroth'],
    'Ayane': ['Shadowbane Ayane', 'Shadowbane Ayane Emerald', 'Shadowbane Ayane Red Hood', 'Shadowbane Ayane Enchanted Lavender', 'Shadowbane Ayane Redempting Light', 'Ayane', 'Obsidian Wraith Ayane', 'Schoolgirl Ayane'],
    'Birdie': ['Warlord Birdie', 'Birdie', 'Professional Weightlifter Birdie', 'Rockstar Birdie', 'Sand Soldier Birdie', 'Infernal Birdie'],
    'Blanka': ['Blanka', 'Blanka Red', 'Professional Baller Blanka', 'Pajama Party Blanka'],
    'Cham Cham': ['Cham Cham', 'Blossom Cham Cham', 'Cham Cham Monochrome', 'Neon Core Cham Cham', 'Pajama Party Cham Cham', 'Pajama Party Cham Cham Cotton Candy', 'Pajama Party Cham Cham Aqua Dream', 'Pajama Party Cham Cham Berry Burst', 'Pajama Party Cham Cham Peachy Keen'],
    'Elphelt': ['Elphelt', 'Cyber Hunter Elphelt', 'Maid Elphelt', 'Summertime Elphelt', 'Schoolgirl Elphelt', 'Goth Elphelt', 'Goth Elphelt Golden', 'Goth Elphelt Crimson Noir', 'Goth Elphelt Midnight Azure', 'Goth Elphelt White'],
    'Erron Black': ['Erron Black', 'Arctic Hunter Erron Black', 'Country Erron Black', 'Mafia Leader Erron Black', 'Neon Core Erron Black'],
    'Ibuki': ['Ibuki', 'Cyber Ninja Ibuki', 'Demon Hunter Ibuki', 'DJ Ibuki', 'Professional Athlete Ibuki', 'Infernal Ibuki', 'Infernal Ibuki Greenfire', 'Infernal Ibuki Silver Flame', 'Infernal Ibuki Golden Flame', 'Infernal Ibuki Blue Flame', 'Lady Deadpool Ibuki'],
    'Juri': ['Primal Warrior Juri','Juri', 'Casual Wear Juri'],
    'Julia': ['Julia', 'Disco Queen Julia', 'Dragon Tamer Julia', 'River Spirit Julia', 'Infernal Julia', 'Schoolgirl Julia', 'River Spirit Julia Golden'],
    'Jun': [ 'Regal Empress Jun', 'Jun', 'Blossom Jun', 'Dragon Tamer Jun', 'Summertime Jun', 'High Elf Jun'],
    'Kotal Kahn': ['Primal Warrior Kotal Kahn', 'Kotal Kahn', 'Cyber Warrior Kotal Kahn', 'Demon Lord Kotal Kahn', 'Summertime Kotal Kahn', 'Forest Warden Kotal Kahn'],
    'Morrigan': ['Morrigan', 'Dragon Tamer Morrigan', 'Neon Core Morrigan', 'High Elf Morrigan', 'High Elf Morrigan Jade', 'High Elf Morrigan Ghost', 'High Elf Morrigan Darkness', 'High Elf Morrigan Silver Crimson', 'Forest Guardian Morrigan'],
    'Nina': ['Nina', 'Arctic Huntress Nina', 'Farmer Nina', 'Summertime Nina'],
    'Noel': ['Arcade Noel', 'Noel', 'Arctic Huntress Noel', 'Officer Noel', 'Captain Noel', 'High Elf Noel'],
    'Peacock': ['Peacock', 'Arctic Huntress Peacock', 'Cyber Bomber Peacock', 'Captain Peacock'],
    'R Mika': ['R Mika', 'Phoenix R Mika', 'Pop Star R Mika', 'Professional Tennis Player R Mika', 'Goth R Mika'],
    'Raiden': ['Arcade Raiden','Raiden', 'Dragon Tamer Raiden', 'Master of Monks Raiden', 'Infernal Raiden', 'Raiden Red', 'Neon Core Raiden', 'Neon Core Raiden Scarlet', 'Neon Core Raiden Emerald', 'Neon Core Raiden Silver', 'Neon Core Raiden White'],
    'Reptile': ['Reptile', 'Blood Predator Reptile', 'Cyber Ninja Reptile', 'Cyber Predator Reptile', 'Summertime Reptile', 'Reptile Sand', 'Goth Reptile'],
    'Scorpion': ['Primal Warrior Scrorpion', 'Scorpion', 'Scorpion Blossom', 'Scorpion Spider', 'Infernal Scorpion', 'Deadpool Scorpion'],
    'Siegfried': ['Siegfried', 'Professional Footballer Siegfried', 'Schoolboy Siegfried', 'Schoolboy Siegfried Azure', 'Schoolboy Siegfried Crimson', 'Schoolboy Siegfried Obisidan Sapphire', 'Schoolboy Siegfried Regal Midnight', 'High Elf Siegfried'],
    'Talim': ['Talim', 'Sand Soldier Talim', 'Talim Bloody', 'Captain Talim', 'Windwood Talim'],
    'Yugo': ['Yugo', 'Arctic Beast Yugo', 'Cyber Predator Yugo', 'Wolverine Yugo'],
    'Shoma': ['Primal Warrior Shoma', 'Shoma', 'Summertime Shoma', 'Pirate Shoma', 'Pirate Shoma Blue', 'Pirate Shoma Jade', 'Pirate Shoma Monochrome', 'Pirate Shoma Violet', 'Shoma Schoolboy', 'Pajama Party Shoma'],
    'Sub Zero': ['Sub Zero','Arcade Sub Zero', 'Arcade Sub Zero Abyssal Depths', 'Arcade Sub Zero Frosty Forest', 'Arcade Sub Zero Cybernetic Surge', 'Arcade Sub Zero Galactic Void', 'Arcane Sorcerer Sub Zero', 'Neon Core Sub Zero'],
    'Christie': ['Arcade Christie', 'Christie', 'Chris T', 'Pajama Party Christie'],
    'Kokoro': ['Kokoro', 'Schoolgirl Kokoro', 'Pajama Party Kokoro'],
    'Eagle': ['Eagle', 'High Elf Eagle', 'Goth Eagle'],
    'Sophitia': ['Arcade Sophitia', 'Sophitia', 'Goth Sophitia'],
    'Shizumaru': ['Shizumaru', 'Samurai Shizumaru'],
    'Kagome': ['Primal Huntress Kagome', 'Primal Huntress Kagome Bear', 'Primal Huntress Kagome Tiger', 'Primal Huntress Kagome Leaf', 'Primal Huntress Kagome Leopard', 'Kagome', 'Spectral Archer Kagome'],
    'Kabal': ['Executioner Kabal', 'Kabal', 'Frosted Kabal'],
    'Kuma': ['Panda', 'Kuma'],
    'Alice': ['Alice', 'Mythic Sentinel Alice'],
};