export const Roles = {
    Akuma: "Mage, Mid, Scaling",
    Alice: "Tank, Jungle, CC",
    Angel: "Support, Enchanter, Mage, Poke",
    Astaroth: "Top, Tank, Teamfight",
    Ayane: "Mid, Assassin, Execute",
    Birdie: "Top, Jungle, Support, CC, Tank",
    Blanka: "Jungle, Tank, Teamfight, CC",
    "Cham Cham": "Jungle, Fighter, 1v1",
    Christie: "Fighter, Top, 1v1",
    Eagle: "Adc, On-hit",
    Elphelt: "Adc, CC, Ability-based",
    FANG: "Support, Healer",
    Ibuki: "Assassin, Poke, Teamfight",
    Julia: "Healer, Support, Vision",
    Jun: "Sustain, Top, Fighter, Vision",
    Kabal: "Jungle, Fighter, Roamer",
    Kokoro: "Healer, Enchanter, Support, Sustain",
    "Kotal Kahn": "Support, Jungle, Healer, Teamfight, Roamer, Tank",
    Kuma: "Support, Tank, CC",
    Lili: "Fighter, Top, 1v1",
    "Mega Man": "Adc, Spell-based",
    Morrigan: "Mage, Burst, Sustain, Mid",
    Nina: "Adc, On-hit, Execute",
    Noel: "Adc, spell-based, Teamfight",
    Peacock: "Adc, Spellbased, Anti-tank",
    "R Mika": "Support, Tank, Buffer, CC",
    Raiden: "mage, Mid, Control",
    Reptile: "Assassin, Jungle, Backline-killer",
    Scorpion: "Assassin, Jungle, Backline-killer, Anti-tank",
    Shinnok: "Mage, Mid, Scaling",
    Shizumaru: "Assassin, Mid",
    Shoma: "Support, Tank, Buffer",
    Siegfried: "Top, Fighter, Sustain, Teamfight",
    Sophitia: "Top, Tank, Teamfight",
    "Sub Zero": "Mid, Support, CC, Burst",
    Talim: "Jungle, Assassin",
    Yugo: "Top, Fighter"
}; 