export const skinToBaseCharacterMap = {
    'Akuma': 'Akuma',
    'Angel': 'Angel',
    'Arctic Beast Yugo': 'Yugo',
    'Arctic Hunter Erron Black': 'Erron Black',
    'Arctic Huntress Nina': 'Nina',
    'Arctic Huntress Noel': 'Noel',
    'Arctic Huntress Peacock': 'Peacock',
    'Arctic Monster Astaroth': 'Astaroth',
    'Astaroth': 'Astaroth',
    'Ayane': 'Ayane',
    'Bunny Ayane': 'Ayane',
    'Birdie': 'Birdie',
    'Blanka': 'Blanka',
    'Blood Predator Reptile': 'Reptile',
    'Blossom Angel': 'Angel',
    'Blossom Cham Cham': 'Cham Cham',
    'Blossom Julia': 'Julia',
    'Blossom Jun': 'Jun',
    'Blossom Mai': 'Mai',
    'Blossom Panda': 'Kuma',
    'Blossom Raiden': 'Raiden',
    'Blossom Shizumaru': 'Shizumaru',
    'Blossom Talim': 'Talim',
    'Scorpion Blossom': 'Scorpion',
    'Cham Cham': 'Cham Cham',
    'Cham Cham Monochrome': 'Cham Cham',
    'Cham Cham Desert': 'Cham Cham',
    'Country Erron Black': 'Erron Black',
    'Cyber Bomber Peacock': 'Peacock',
    'Cyber Hunter Elphelt': 'Elphelt',
    'Cyber Ninja Reptile': 'Reptile',
    'Cyber Ninja Ibuki': 'Ibuki',
    'Cyber Predator Yugo': 'Yugo',
    'Cyber Predator Reptile': 'Reptile',
    'Cyber Warrior Kotal Kahn': 'Kotal Kahn',
    'Demon Hunter Ibuki': 'Ibuki',
    'Demon Lord Kotal Kahn': 'Kotal Kahn',
    'Desert Demon Shizumaru': 'Shizumaru',
    'Disco Queen Julia': 'Julia',
    'DJ Ibuki': 'Ibuki',
    'Dragon Tamer Julia': 'Julia',
    'Dragon Tamer Jun': 'Jun',
    'Dragon Tamer Morrigan': 'Morrigan',
    'Dragon Tamer Raiden': 'Raiden',
    'Elphelt': 'Elphelt',
    'Blanka Red': 'Blanka',
    'Erron Black': 'Erron Black',
    'Farmer Nina': 'Nina',
    'Ibuki': 'Ibuki',
    'Julia': 'Julia',
    'Jun': 'Jun',
    'Kotal Kahn': 'Kotal Kahn',
    'Mafia Leader Erron Black': 'Erron Black',
    'Maid Elphelt': 'Elphelt',
    'Master of Monks Raiden': 'Raiden',
    'Morrigan': 'Morrigan',
    'Neon Core Morrigan': 'Morrigan',
    'Nina': 'Nina',
    'Noel': 'Noel',
    'Obsidian Wraith Ayane': 'Ayane',
    'Officer Noel': 'Noel',
    'Peacock': 'Peacock',
    'Phoenix R Mika': 'R Mika',
    'Pop Star R Mika': 'R Mika',
    'Professional Athlete Ibuki': 'Ibuki',
    'Professional Weightlifter Birdie': 'Birdie',
    'Professional Baller Blanka': 'Blanka',
    'Professional Footballer Siegfried': 'Siegfried',
    'Professional Tennis Player R Mika': 'R Mika',
    'R Mika': 'R Mika',
    'Raiden': 'Raiden',
    'Ibuki Red': 'Ibuki',
    'Reptile': 'Reptile',
    'River Spirit Julia': 'Julia',
    'Rockstar Akuma': 'Akuma',
    'Rockstar Birdie': 'Birdie',
    'Royal Guard Astaroth': 'Astaroth',
    'Sand Soldier Astaroth': 'Astaroth',
    'Sand Soldier Birdie': 'Birdie',
    'Sand Soldier Talim': 'Talim',
    'Sand Soldier Shoma': 'Shoma',
    'Sand Soldier Blanka': 'Blanka',
    'Sand Soldier Kotal Kahn': 'Kotal Kahn',
    'Sand Soldier Jun': 'Jun',
    'Sand Soldier Akuma': 'Akuma',
    'Sand Soldier Scorpion': 'Scorpion',
    'Scorpion': 'Scorpion',
    'Siegfried': 'Siegfried',
    'Scorpion Spider': 'Scorpion',
    'Street Fighter Hugo': 'Hugo',
    'Superhero Shizumaru': 'Shizumaru',
    'Summertime Elphelt': 'Elphelt',
    'Summertime Jun': 'Jun',
    'Summertime Kotal Kahn': 'Kotal Kahn',
    'Summertime Nina': 'Nina',
    'Summertime Reptile': 'Reptile',
    'Summertime Shoma': 'Shoma',
    'Shoma': 'Shoma',
    'Skater Shoma': 'Shoma',
    'Juri': 'Juri',
    'Casual Wear Juri': 'Juri',
    'Winter Festival Juri': 'Juri',
    'Winter Festival Lili': 'Lili',
    'Winter Festival Lili Holiday': 'Lili',
    'Winter Festival Lili Snowy Blush': 'Lili',
    'Winter Festival Lili Golden': 'Lili',
    'Winter Festival Lili Snowflake': 'Lili',
    'Winter Festival Shizumaru': 'Shizumaru',
    'Winter Festival Mai': 'Mai',
    'Winter Festival Kuma': 'Kuma',
    'Winter Festival Kabal': 'Kabal',
    'Winter Queen Angel': 'Angel',
    'Infernal Raiden': 'Raiden',
    'Infernal Birdie': 'Birdie',
    'Infernal Ibuki': 'Ibuki',
    'Infernal Ibuki Greenfire': 'Ibuki',
    'Infernal Astaroth': 'Astaroth',
    'Infernal Scorpion': 'Scorpion',
    'Raiden Red': 'Raiden',
    'Infernal Ibuki Silver Flame': 'Ibuki',
    'Infernal Ibuki Golden Flame': 'Ibuki',
    'Infernal Ibuki Blue Flame': 'Ibuki',
    'Arcane Sorcerer Sub Zero': 'Sub Zero',
    'Captain Akuma': 'Akuma',
    'Captain Talim': 'Talim',
    'Captain Peacock': 'Peacock',
    'Captain Noel': 'Noel',
    'Pirate Shoma': 'Shoma',
    'Pirate Shoma Jade': 'Shoma',
    'Pirate Shoma Blue': 'Shoma',
    'Pirate Shoma Monochrome': 'Shoma',
    'Pirate Shoma Violet': 'Shoma',
    'Neon Core Angel': 'Angel',
    'Neon Core Cham Cham': 'Cham Cham',
    'Neon Core Erron Black': 'Erron Black',
    'Neon Core Raiden Emerald': 'Raiden',
    'Neon Core Raiden White': 'Raiden',
    'Neon Core Raiden Silver': 'Raiden',
    'Neon Core Raiden Scarlet': 'Raiden',
    'Neon Core Sub Zero': 'Sub Zero',
    'Chris T': 'Christie',
    'Christie': 'Christie',
    'Kokoro': 'Kokoro',
    'Schoolgirl Kokoro': 'Kokoro',
    'Infernal Julia': 'Julia',
    'Schoolgirl Julia': 'Julia',
    'Schoolgirl Elphelt': 'Elphelt',
    'Schoolboy Siegfried': 'Siegfried',
    'Shoma Schoolboy': 'Shoma',
    'Schoolgirl Ayane': 'Ayane',
    'Schoolboy Siegfried Azure': 'Siegfried',
    'Schoolboy Siegfried Crimson': 'Siegfried',
    'Schoolboy Siegfried Obisidan Sapphire': 'Siegfried',
    'Schoolboy Siegfried Regal Midnight': 'Siegfried',
    'High Elf Siegfried': 'Siegfried',
    'High Elf Eagle': 'Eagle',
    'High Elf Morrigan': 'Morrigan',
    'High Elf Morrigan Jade': 'Morrigan',
    'High Elf Morrigan Ghost': 'Morrigan',
    'High Elf Morrigan Darkness': 'Morrigan',
    'High Elf Morrigan Silver Crimson': 'Morrigan',
    'High Elf Morrigan': 'Morrigan',
    'High Elf Noel': 'Noel',
    'High Elf Akuma': 'Akuma',
    'High Elf Jun': 'Jun',
    'Goth Sophitia': 'Sophitia',
    'Goth Elphelt': 'Elphelt',
    'Goth Elphelt Golden': 'Elphelt',
    'Goth Elphelt Crimson Noir': 'Elphelt',
    'Goth Elphelt Midnight Azure': 'Elphelt',
    'Goth Elphelt White': 'Elphelt',
    'Goth Eagle': 'Eagle',
    'Goth Reptile': 'Reptile',
    'Goth R Mika': 'R Mika',
    'Sophitia': 'Sophitia',
    'Deadpool Scorpion': 'Scorpion',
    'Lady Deadpool Ibuki': 'Ibuki',
    'Wolverine Yugo': 'Yugo',
    'Pajama Party Blanka': 'Blanka',
    'Pajama Party Shoma': 'Shoma',
    'Pajama Party Kokoro': 'Kokoro',
    'Pajama Party Cham Cham' : 'Cham Cham',
    'Pajama Party Cham Cham Cotton Candy': 'Cham Cham',
    'Pajama Party Cham Cham Aqua Dream': 'Cham Cham',
    'Pajama Party Cham Cham Berry Burst': 'Cham Cham',
    'Pajama Party Cham Cham Peachy Keen': 'Cham Cham',
    'Pajama Party Christie': 'Christie',
    'Samurai Shizumaru': 'Shizumaru',
    'Shizumaru': 'Shizumaru',
    'Spectral Archer Kagome': 'Kagome',
    'Forest Behemoth Astaroth': 'Astaroth',
    'Forest Behemoth Astaroth Gilded': 'Astaroth',
    'Forest Behemoth Astaroth Opulent': 'Astaroth',
    'Forest Behemoth Astaroth Rosy': 'Astaroth',
    'Forest Behemoth Astaroth Ashen': 'Astaroth',
    'Forest Guardian Morrigan': 'Morrigan',
    'Forest Goddess Angel': 'Angel',
    'Windwood Talim': 'Talim',
    'Forest Warden Kotal Kahn': 'Kotal Kahn',
    'River Spirit Julia Golden': 'Julia',
    'Frosted Kabal': 'Kabal',
    'Kabal': 'Kabal',
    'Arcade Sub Zero Abyssal Depths': 'Sub Zero',
    'Arcade Sub Zero Frosty Forest': 'Sub Zero',
    'Arcade Sub Zero Cybernetic Surge': 'Sub Zero',
    'Arcade Sub Zero Galactic Void': 'Sub Zero',
    'Arcade Raiden': 'Raiden',
    'Arcade Sophitia': 'Sophitia',
    'Arcade Christie': 'Christie',
    'Arcade Noel': 'Noel',
    'Primal Huntress Kagome': 'Kagome',
    'Primal Huntress Kagome Bear': 'Kagome',
    'Primal Huntress Kagome Tiger': 'Kagome',
    'Primal Huntress Kagome Leaf': 'Kagome',
    'Primal Huntress Kagome Leopard': 'Kagome',
    'Primal Warrior Shoma': 'Shoma',
    'Primal Warrior Scorpion': 'Scorpion',
    'Primal Warrior Juri': 'Juri',
    'Primal Warrior Kotal Kahn': 'Kotal Kahn',
    'Kuma': 'Kuma',
    'Panda': 'Kuma',
    'Arcade Sub Zero': 'Sub Zero',
    'Alice': 'Alice',
    'Mythic Sentinel Alice': 'Alice',
    'Regal Empress Jun': 'Jun',
    'Warlord Birdie': 'Birdie',
    'Shadowbane Ayane': 'Ayane',
    'Shadowbane Ayane Emerald': 'Ayane',
    'Shadowbane Ayane Red Hood': 'Ayane',
    'Shadowbane Ayane Enchanted Lavender': 'Ayane',
    'Shadowbane Ayane Redempting Light': 'Ayane',
    'Executioner Kabal': 'Kabal',
    'Stonebreaker Astaroth': 'Astaroth',
    'Rainy Day Shinnok': 'Shinnok',
    'Rainy Day R Mika': 'R Mika',
    'Rainy Day R Mika Ocean': 'R Mika',
    'Rainy Day R Mika Twilight': 'R Mika',
    'Rainy Day R Mika Moss': 'R Mika',
    'Rainy Day R Mika Rose': 'R Mika',
    'Rainy Day Julia': 'Julia',
    'Rainy Day Shizumaru': 'Shizumaru',
    'Rainy Day Reptile': 'Reptile',
    'Rainy Day Noel': 'Noel',
    'FANG': 'FANG',
    'Voidborn FANG': 'FANG',
    'Voidborn Nina': 'Nina',
    'Voidborn Nina Neon Eclipse': 'Nina',
    'Voidborn Nina Desert': 'Nina',
    'Voidborn Nina Warlock': 'Nina',
    'Voidborn Nina Devil Countess': 'Nina',
    'Voidborn Blanka': 'Blanka',
    'Voidborn Akuma': 'Akuma',
    'Voidborn Peacock': 'Peacock',
    'Voidborn Scorpion': 'Scorpion',
    'Witch Julia': 'Julia',
    'Witch Julia Nature': 'Julia',
    'Witch Julia Wicked': 'Julia',
    'Witch Julia Scarlet': 'Julia',
    'Witch Julia Enchanted': 'Julia',
    'Diablo Erron Black': 'Erron Black',
    'Zombie Astaroth': 'Astaroth',
    'Jack O Blanka': 'Blanka',
    'Spectral Reaper Ayane': 'Ayane',
    'Battle Bistro Kuma': 'Kuma',
    'Battle Bistro Sophitia': 'Sophitia',
    'Battle Bistro Akuma': 'Akuma',
    'Battle Bistro Shizumaru': 'Shizumaru',
    'Battle Bistro Lili': 'Lili',
    'Lili': 'Lili',
    'Battle Bistro Shizumaru Sweet': 'Shizumaru',
    'Battle Bistro Shizumaru Fast Food': 'Shizumaru',
    'Battle Bistro Shizumaru Blackberry': 'Shizumaru',
    'Battle Bistro Shizumaru Frosted Whisk': 'Shizumaru',
    'Jade Siegfried': 'Siegfried',
    'Jade Ayane': 'Ayane',
    'Jade Yugo': 'Yugo',
    'Jade Scorpion': 'Scorpion',
    'Jade Panda': 'Kuma',
    'Jade Scorpion Bloodstone': 'Scorpion',
    'Jade Scorpion Topaz': 'Scorpion',
    'Jade Scorpion Rose Quartz': 'Scorpion',
    'Jade Scorpion Agate': 'Scorpion',
    'Mega Man': 'Mega Man',
    'Pyromancer Mega Man': 'Mega Man',
    'Sacred Ceremony Julia Romance': 'Julia',
    'Sacred Ceremony Julia Sweetheart': 'Julia',
    'Sacred Ceremony Julia Champagne': 'Julia',
    'Sacred Ceremony Julia Black Velvet': 'Julia',
    'Sacred Ceremony Morrigan': 'Morrigan',
    'Sacred Ceremony Birdie': 'Birdie',
    'Sacred Ceremony Shoma': 'Shoma',
    'Sacred Ceremony Nina': 'Nina',
    'Sacred Ceremony Julia': 'Julia',
    'Farmer Cham Cham': 'Cham Cham',
    'Farmer Raiden': 'Raiden',
    'Farmer Alice': 'Alice',
    'Farmer FANG': 'FANG',
    'Farmer Shoma': 'Shoma',
    'Farmer Nina Blue': 'Nina',
    'Akuma Elder': 'Akuma',
    'Akuma Enraged': 'Akuma',
    'Akuma Master': 'Akuma',
    'Angel Dark Clouds': 'Angel',
    'Angel Heaven': 'Angel',
    'Angel Jade': 'Angel',
    'Astaroth Crystal': 'Astaroth',
    'Astaroth Poison': 'Astaroth',
    'Astaroth Rage': 'Astaroth',
    'Ayane Cold': 'Ayane',
    'Ayane Sunset': 'Ayane',
    'Ayane Wild': 'Ayane',
    'Birdie Metal': 'Birdie',
    'Birdie Rich': 'Birdie',
    'Birdie Toxic': 'Birdie',
    'Blanka Black': 'Blanka',
    'Blanka Dawn': 'Blanka',
    'Blanka Sand': 'Blanka',
    'Cham Cham Autumn': 'Cham Cham',
    'Cham Cham Punk': 'Cham Cham',
    'Cham Cham Spring': 'Cham Cham',
    'Christie Black': 'Christie',
    'Christie Samba': 'Christie',
    'Christie Wind': 'Christie',
    'Eagle Black': 'Eagle',
    'Eagle Green': 'Eagle',
    'Eagle Purple': 'Eagle',
    'Elphelt Black': 'Elphelt',
    'Elphelt Ocean': 'Elphelt',
    'Elphelt Shiny': 'Elphelt',
    'Erron Black Demon': 'Erron Black',
    'Erron Black Poker': 'Erron Black',
    'Erron Black White': 'Erron Black',
    'FANG Dark': 'FANG',
    'FANG Poison': 'FANG',
    'FANG Trader': 'FANG',
    'Feather Dancer Mai': 'Mai',
    'Ibuki Red': 'Ibuki',
    'Ibuki Shadow': 'Ibuki',
    'Ibuki Yellow': 'Ibuki',
    'Julia Blue': 'Julia',
    'Julia Golden': 'Julia',
    'Julia Red': 'Julia',
    'Jun Bloodmoon': 'Jun',
    'Jun Golden': 'Jun',
    'Jun Heaven': 'Jun',
    'Jun Unknown': 'Jun',
    'Juri Blue': 'Juri',
    'Juri Dark': 'Juri',
    'Juri Monochrome': 'Juri',
    'Juri Quinn': 'Juri',
    'Juri Red': 'Juri',
    'Juri Showstopper': 'Juri',
    'Juri Villain': 'Juri',
    'Kabal Blue': 'Kabal',
    'Kabal Red': 'Kabal',
    'Kabal Yellow': 'Kabal',
    'Kagome Bubblegum': 'Kagome',
    'Kagome Ocean': 'Kagome',
    'Kagome Red': 'Kagome',
    'Kokoro Black': 'Kokoro',
    'Kokoro Flowerstorm': 'Kokoro',
    'Kokoro Red Rose': 'Kokoro',
    'Kotal Kahn Golden': 'Kotal Kahn',
    'Kotal Kahn Leader': 'Kotal Kahn',
    'Kotal Kahn Warrior': 'Kotal Kahn',
    'Kuma Black': 'Kuma',
    'Kuma Hunter': 'Kuma',
    'Kuma Pink': 'Kuma',
    'Lili Dark': 'Lili',
    'Lili Golden': 'Lili',
    'Lili Red': 'Lili',
    'Mai': 'Mai',
    'Mai Blue': 'Mai',
    'Mai Grey': 'Mai',
    'Mai Light': 'Mai',
    'Mega Man Evil': 'Mega Man',
    'Mega Man Monochrome': 'Mega Man',
    'Mega Man Violet': 'Mega Man',
    'Morrigan Charm': 'Morrigan',
    'Morrigan Midnight': 'Morrigan',
    'Morrigan Punk': 'Morrigan',
    'Nina Black Widow': 'Nina',
    'Nina Casual': 'Nina',
    'Nina Red Leopard': 'Nina',
    'Nina Sunset': 'Nina',
    'Noel Black': 'Noel',
    'Noel Bubblegum': 'Noel',
    'Noel Crimson': 'Noel',
    'Peacock Hero': 'Peacock',
    'Peacock Lucky': 'Peacock',
    'Peacock Steampunk': 'Peacock',
    'Peacock White': 'Peacock',
    'R Mika Dancer Mai': 'R Mika',
    'R Mika Quinn': 'R Mika',
    'R Mika Showstopper': 'R Mika',
    'R Mika Villain': 'R Mika',
    'Raiden Dark': 'Raiden',
    'Raiden Lightning': 'Raiden',
    'Raiden Purple Storm': 'Raiden',
    'Raiden Silver': 'Raiden',
    'Raiden Storm': 'Raiden',
    'Raiden Yellow Lightning': 'Raiden',
    'Reptile Golden': 'Reptile',
    'Reptile Toxic': 'Reptile',
    'Reptile Warlord': 'Reptile',
    'Scorpion Champion': 'Scorpion',
    'Scorpion Dark Clouds': 'Scorpion',
    'Scorpion Heaven': 'Scorpion',
    'Scorpion Icy': 'Scorpion',
    'Scorpion Sand': 'Scorpion',
    'Shinnok Dark Mage': 'Shinnok',
    'Shinnok Enchanter': 'Shinnok',
    'Shinnok Warlock': 'Shinnok',
    'Shizumaru Dark': 'Shizumaru',
    'Shizumaru Light': 'Shizumaru',
    'Shizumaru Punch': 'Shizumaru',
    'Shoma Green': 'Shoma',
    'Shoma Red': 'Shoma',
    'Shoma Silver': 'Shoma',
    'Siegfried Copper': 'Siegfried',
    'Siegfried Dark': 'Siegfried',
    'Siegfried Hero': 'Siegfried',
    'Siegfried Silver': 'Siegfried',
    'Sophitia Dark': 'Sophitia',
    'Sophitia Dawn': 'Sophitia',
    'Sophitia Sunset': 'Sophitia',
    'Sub Zero Frostbite': 'Sub Zero',
    'Sub Zero Frozen': 'Sub Zero',
    'Sub Zero Tundra': 'Sub Zero',
    'Talim Red': 'Talim',
    'Talim River': 'Talim',
    'Talim Sunset': 'Talim',
    'Yugo Blood Hunter': 'Yugo',
    'Yugo Night': 'Yugo',
    'Yugo Silver Wolf': 'Yugo',
    'Steamcore MegaMan': 'Mega Man',
    'Steamcore MegaMan Copper': 'Mega Man',
    'Steamcore MegaMan Golden': 'Mega Man',
    'Steamcore MegaMan Silver': 'Mega Man',
    'Steamcore MegaMan Metal': 'Mega Man',
    'Steampunk Ibuki': 'Ibuki',
    'Steamforged Nina': 'Nina',
    'Steamforged Kabal': 'Kabal',
    'Steamforged Yugo': 'Yugo',
    'Atlantean Zasalamel': 'Zasalamel',
    'Zasalamel': 'Zasalamel',
    'Zasalamel Evil': 'Zasalamel',
    'Zasalamel Scarlet': 'Zasalamel',
    'Zasalamel Sorcerer': 'Zasalamel',
    'Atlantean Christie': 'Christie',
    'Atlantean Kotal Kahn': 'Kotal Kahn',
    'Atlantean Shinnok': 'Shinnok',
    'Atlantean Sub Zero': 'Sub Zero',
    'Atlantean Kagome': 'Kagome',
    'Lunar Festival Lili': 'Lili',
    'Lunar Festival Scorpion': 'Scorpion',
    'Lunar Festival Kokoro': 'Kokoro',
    'Lunar Festival Kokoro Sweet': 'Kokoro',
    'Lunar Festival Reptile': 'Reptile',
    'Lunar Festival Noel': 'Noel',
    'Lunar Festival Siegfried': 'Siegfried',
    'Heartbreaker Ibuki': 'Ibuki',
    'Date Night Kuma': 'Kuma',
    'Date Night Mega Man': 'Mega Man',
    'Lovely Sophitia': 'Sophitia',
    'Lovely Kagome': 'Kagome',
    'Celestial Protector Cham Cham': 'Cham Cham',
    'Celestial Protector Elphelt': 'Elphelt',
    'Celestial Protector Juri': 'Juri',
    'Celestial Protector Lili': 'Lili',
    'Celestial Protector R Mika': 'R Mika',
    'Celestial Protector Sophitia': 'Sophitia',
    'Battleborn Zasalamel': 'Zasalamel',
    'Battleborn Talim': 'Talim',
    'Battleborn Yugo': 'Yugo',
    'Battleborn Eagle': 'Eagle',
    'Battleborn Ayane': 'Ayane',
    'Thunderstrike Shao Kahn': 'Shao Kahn',
    'Shao Kahn': 'Shao Kahn',
    'Shao Kahn Demon': 'Shao Kahn',
    'Shao Kahn Metal': 'Shao Kahn',
    'Shao Kahn Molten': 'Shao Kahn',
    'Glorious Julia': 'Julia',
    'Gangster Juri': 'Juri',
    'Gangster Blanka': 'Blanka',
    'Gangster Peacock': 'Peacock',
    'Bandito Reptile': 'Reptile',
    'Bandito Eagle': 'Eagle',
    'Bandito Shinnok': 'Shinnok',
    'Bandito Shinnok Fel Fire': 'Shinnok',
    'Chocolate Bunny Alice': 'Alice',
    'Easter Bunny Peacock': 'Peacock',
    'Easter Bunny R Mika': 'R Mika',
    'Easter Bunny Shinnok': 'Shinnok',
    'Tanya': 'Tanya',
    'Water Dancer Tanya': 'Tanya',
    'Reptile Sand': 'Reptile',
    'Thunder God Akuma': 'Akuma',
    'Talim Bloody': 'Talim',
    'Underworld Demon Noel': 'Noel',
    'Voidborn Angel': 'Angel',
    'Yugo': 'Yugo',
    'Talim': 'Talim',
    'Tokyo Mew Mew Ayane': 'Ayane',
    'Tokyo Mew Mew Julia': 'Julia',
    'Tokyo Mew Mew Kagome': 'Kagome',
    'Tokyo Mew Mew Lili': 'Lili',
    'Tokyo Mew Mew Cham Cham': 'Cham Cham',
    'Monster Trainer Ayane': 'Ayane',
    'Monster Trainer Eagle': 'Eagle',
    'Monster Trainer FANG': 'FANG',
    'Monster Trainer Kokoro': 'Kokoro',
    'Monster Trainer Kotal Kahn': 'Kotal Kahn',
    'Monster Trainer Lili': 'Lili',
    'Monster Trainer Peacock': 'Peacock',
    'Monster Trainer Shoma': 'Shoma',
};