export const skinToBaseCharacterMap = {
    'Akuma': 'Akuma',
    'Angel': 'Angel',
    'Arctic Beast Yugo': 'Yugo',
    'Arctic Hunter Erron Black': 'Erron Black',
    'Arctic Huntress Nina': 'Nina',
    'Arctic Huntress Noel': 'Noel',
    'Arctic Huntress Peacock': 'Peacock',
    'Arctic Monster Astaroth': 'Astaroth',
    'Astaroth': 'Astaroth',
    'Ayane': 'Ayane',
    'Birdie': 'Birdie',
    'Blanka': 'Blanka',
    'Blood Predator Reptile': 'Reptile',
    'Blossom Angel': 'Angel',
    'Blossom Cham Cham': 'Cham Cham',
    'Blossom Jun': 'Jun',
    'Scorpion Blossom': 'Scorpion',
    'Cham Cham': 'Cham Cham',
    'Country Erron Black': 'Erron Black',
    'Cyber Bomber Peacock': 'Peacock',
    'Cyber Hunter Elphelt': 'Elphelt',
    'Cyber Ninja Reptile': 'Reptile',
    'Cyber Ninja Ibuki': 'Ibuki',
    'Cyber Predator Yugo': 'Yugo',
    'Cyber Predator Reptile': 'Reptile',
    'Cyber Warrior Kotal Kahn': 'Kotal Kahn',
    'Demon Hunter Ibuki': 'Ibuki',
    'Demon Lord Kotal Kahn': 'Kotal Kahn',
    'Disco Queen Julia': 'Julia',
    'DJ Ibuki': 'Ibuki',
    'Dragon Tamer Julia': 'Julia',
    'Dragon Tamer Jun': 'Jun',
    'Dragon Tamer Morrigan': 'Morrigan',
    'Dragon Tamer Raiden': 'Raiden',
    'Elphelt': 'Elphelt',
    'Blanka Red': 'Blanka',
    'Erron Black': 'Erron Black',
    'Farmer Nina': 'Nina',
    'Ibuki': 'Ibuki',
    'Julia': 'Julia',
    'Jun': 'Jun',
    'Kotal Kahn': 'Kotal Kahn',
    'Mafia Leader Erron Black': 'Erron Black',
    'Maid Elphelt': 'Elphelt',
    'Master of Monks Raiden': 'Raiden',
    'Morrigan': 'Morrigan',
    'Neon Core Morrigan': 'Morrigan',
    'Nina': 'Nina',
    'Noel': 'Noel',
    'Obsidian Wraith Ayane': 'Ayane',
    'Officer Noel': 'Noel',
    'Peacock': 'Peacock',
    'Phoenix R Mika': 'R Mika',
    'Pop Star R Mika': 'R Mika',
    'Professional Athlete Ibuki': 'Ibuki',
    'Professional Weightlifter Birdie': 'Birdie',
    'Professional Baller Blanka': 'Blanka',
    'Professional Footballer Siegfried': 'Siegfried',
    'Professional Tennis Player R Mika': 'R Mika',
    'R Mika': 'R Mika',
    'Raiden': 'Raiden',
    'Ibuki Red': 'Ibuki',
    'Reptile': 'Reptile',
    'River Spirit Julia': 'Julia',
    'Rockstar Akuma': 'Akuma',
    'Rockstar Birdie': 'Birdie',
    'Royal Guard Astaroth': 'Astaroth',
    'Sand Soldier Astaroth': 'Astaroth',
    'Sand Soldier Birdie': 'Birdie',
    'Reptile Sand': 'Reptile',
    'Sand Soldier Talim': 'Talim',
    'Scorpion': 'Scorpion',
    'Siegfried': 'Siegfried',
    'Scorpion Spider': 'Scorpion',
    'Street Fighter Hugo': 'Hugo',
    'Talim': 'Talim',
    'Thunder God Akuma': 'Akuma',
    'Talim Bloody': 'Talim',
    'Voidborn Angel': 'Angel',
    'Yugo': 'Yugo',
    'Summertime Elphelt': 'Elphelt',
    'Summertime Jun': 'Jun',
    'Summertime Kotal Kahn': 'Kotal Kahn',
    'Summertime Nina': 'Nina',
    'Summertime Reptile': 'Reptile',
    'Summertime Shoma': 'Shoma',
    'Shoma': 'Shoma',
    'Juri': 'Juri',
    'Casual Wear Juri': 'Juri',
    'Infernal Raiden': 'Raiden',
    'Infernal Birdie': 'Birdie',
    'Infernal Ibuki': 'Ibuki',
    'Infernal Ibuki Greenfire': 'Ibuki',
    'Infernal Astaroth': 'Astaroth',
    'Infernal Scorpion': 'Scorpion',
    'Cham Cham Monochrome': 'Cham Cham',
    'Raiden Red': 'Raiden',
    'Infernal Ibuki Silver Flame': 'Ibuki',
    'Infernal Ibuki Golden Flame': 'Ibuki',
    'Infernal Ibuki Blue Flame': 'Ibuki',
    'Arcane Sorcerer Sub Zero': 'Sub Zero',
    'Captain Akuma': 'Akuma',
    'Captain Talim': 'Talim',
    'Captain Peacock': 'Peacock',
    'Captain Noel': 'Noel',
    'Pirate Shoma': 'Shoma',
    'Pirate Shoma Jade': 'Shoma',
    'Pirate Shoma Blue': 'Shoma',
    'Pirate Shoma Monochrome': 'Shoma',
    'Pirate Shoma Violet': 'Shoma',
    'Neon Core Angel': 'Angel',
    'Neon Core Cham Cham': 'Cham Cham',
    'Neon Core Erron Black': 'Erron Black',
    'Neon Core Raiden Emerald': 'Raiden',
    'Neon Core Raiden White': 'Raiden',
    'Neon Core Raiden Silver': 'Raiden',
    'Neon Core Raiden Scarlet': 'Raiden',
    'Neon Core Sub Zero': 'Sub Zero',
    'Chris T': 'Christie',
    'Christie': 'Christie',
    'Kokoro': 'Kokoro',
    'Schoolgirl Kokoro': 'Kokoro',
    'Infernal Julia': 'Julia',
    'Schoolgirl Julia': 'Julia',
    'Schoolgirl Elphelt': 'Elphelt',
    'Schoolboy Siegfried': 'Siegfried',
    'Shoma Schoolboy': 'Shoma',
    'Schoolgirl Ayane': 'Ayane',
    'Schoolboy Siegfried Azure': 'Siegfried',
    'Schoolboy Siegfried Crimson': 'Siegfried',
    'Schoolboy Siegfried Obisidan Sapphire': 'Siegfried',
    'Schoolboy Siegfried Regal Midnight': 'Siegfried',
    'High Elf Siegfried': 'Siegfried',
    'High Elf Eagle': 'Eagle',
    'High Elf Morrigan': 'Morrigan',
    'High Elf Morrigan Jade': 'Morrigan',
    'High Elf Morrigan Ghost': 'Morrigan',
    'High Elf Morrigan Darkness': 'Morrigan',
    'High Elf Morrigan Silver Crimson': 'Morrigan',
    'High Elf Noel': 'Noel',
    'High Elf Akuma': 'Akuma',
    'High Elf Jun': 'Jun',
    'Goth Sophitia': 'Sophitia',
    'Goth Elphelt': 'Elphelt',
    'Goth Elphelt Golden': 'Elphelt',
    'Goth Elphelt Crimson Noir': 'Elphelt',
    'Goth Elphelt Midnight Azure': 'Elphelt',
    'Goth Elphelt White': 'Elphelt',
    'Goth Eagle': 'Eagle',
    'Goth Reptile': 'Reptile',
    'Goth R Mika': 'R Mika',
    'Sophitia': 'Sophitia',
    'Deadpool Scorpion': 'Scorpion',
    'Lady Deadpool Ibuki': 'Ibuki',
    'Wolverine Yugo': 'Yugo',
    'Pajama Party Blanka': 'Blanka',
    'Pajama Party Shoma': 'Shoma',
    'Pajama Party Kokoro': 'Kokoro',
    'Pajama Party Cham Cham' : 'Cham Cham',
    'Pajama Party Cham Cham Cotton Candy': 'Cham Cham',
    'Pajama Party Cham Cham Aqua Dream': 'Cham Cham',
    'Pajama Party Cham Cham Berry Burst': 'Cham Cham',
    'Pajama Party Cham Cham Peachy Keen': 'Cham Cham',
    'Pajama Party Christie': 'Christie',
    'Samurai Shizumaru': 'Shizumaru',
    'Shizumaru': 'Shizumaru',
    'Spectral Archer Kagome': 'Kagome',
    'Forest Behemoth Astaroth': 'Astaroth',
    'Forest Behemoth Astaroth Gilded': 'Astaroth',
    'Forest Behemoth Astaroth Opulent': 'Astaroth',
    'Forest Behemoth Astaroth Rosy': 'Astaroth',
    'Forest Behemoth Astaroth Ashen': 'Astaroth',
    'Forest Guardian Morrigan': 'Morrigan',
    'Forest Goddess Angel': 'Angel',
    'Windwood Talim': 'Talim',
    'Forest Warden Kotal Kahn': 'Kotal Kahn',
    'River Spirit Julia Golden': 'Julia',
    'Frosted Kabal': 'Kabal',
    'Kabal': 'Kabal',
    'Arcade Sub Zero Abyssal Depths': 'Sub Zero',
    'Arcade Sub Zero Frosty Forest': 'Sub Zero',
    'Arcade Sub Zero Cybernetic Surge': 'Sub Zero',
    'Arcade Sub Zero Galactic Void': 'Sub Zero',
    'Arcade Raiden': 'Raiden',
    'Arcade Sophitia': 'Sophitia',
    'Arcade Christie': 'Christie',
    'Arcade Noel': 'Noel',
    'Primal Huntress Kagome': 'Kagome',
    'Primal Huntress Kagome Bear': 'Kagome',
    'Primal Huntress Kagome Tiger': 'Kagome',
    'Primal Huntress Kagome Leaf': 'Kagome',
    'Primal Huntress Kagome Leopard': 'Kagome',
    'Primal Warrior Shoma': 'Shoma',
    'Primal Warrior Scorpion': 'Scorpion',
    'Primal Warrior Juri': 'Juri',
    'Primal Warrior Kotal Kahn': 'Kotal Kahn',
    'Kuma': 'Kuma',
    'Panda': 'Kuma',
    'Arcade Sub Zero': 'Sub Zero',
    'Alice': 'Alice',
    'Mythic Sentinel Alice': 'Alice',
    'Regal Empress Jun': 'Jun',
    'Warlord Birdie': 'Birdie',
    'Shadowbane Ayane': 'Ayane',
    'Shadowbane Ayane Emerald': 'Ayane',
    'Shadowbane Ayane Red Hood': 'Ayane',
    'Shadowbane Ayane Enchanted Lavender': 'Ayane',
    'Shadowbane Ayane Redempting Light': 'Ayane',
    'Executioner Kabal': 'Kabal',
    'Stonebreaker Astaroth': 'Astaroth',
    'Rainy Day Shinnok': 'Shinnok',
    'Rainy Day R Mika': 'R Mika',
    'Rainy Day R Mika Ocean': 'R Mika',
    'Rainy Day R Mika Twilight': 'R Mika',
    'Rainy Day R Mika Moss': 'R Mika',
    'Rainy Day R Mika Rose': 'R Mika',
    'Rainy Day Julia': 'Julia',
    'Rainy Day Shizumaru': 'Shizumaru',
    'Rainy Day Reptile': 'Reptile',
    'Rainy Day Noel': 'Noel',
    'FANG': 'FANG',
    'Voidborn FANG': 'FANG',
    'Voidborn Nina': 'Nina',
    'Voidborn Nina Neon Eclipse': 'Nina',
    'Voidborn Nina Desert': 'Nina',
    'Voidborn Nina Warlock': 'Nina',
    'Voidborn Nina Devil Countess': 'Nina',
    'Voidborn Blanka': 'Blanka',
    'Voidborn Akuma': 'Akuma',
    'Voidborn Peacock': 'Peacock',
    'Voidborn Scorpion': 'Scorpion',
    'Witch Julia': 'Julia',
    'Witch Julia Nature': 'Julia',
    'Witch Julia Wicked': 'Julia',
    'Witch Julia Scarlet': 'Julia',
    'Witch Julia Enchanted': 'Julia',
    'Diablo Erron Black': 'Erron Black',
    'Zombie Astaroth': 'Astaroth',
    'Jack O Blanka': 'Blanka',
    'Spectral Reaper Ayane': 'Ayane',
};