// Dragon Pulse - A Dragon-type special move
import { BaseMove } from './base_move.js';

export class DragonPulse extends BaseMove {
    constructor() {
        super();
        this.name = "Dragon Pulse";
        this.type = "Dragon";
        this.category = "Special";
        this.power = 85;
        this.accuracy = 100;
        this.pp = 15;
        this.maxPP = 15;
        this.priority = 0;
        this.description = "The target is attacked with a shock wave generated by the user's gaping mouth.";
        this.effects = [];
        this.criticalHitRate = 1;
        this.makesContact = false;
    }

    executeSpecific(user, target, battleManager, battleState, result) {
        // Execute standard damage
        result = this.executeDamageMove(user, target, battleManager, result);

        // TODO: Add special effects here if needed
        
        return result;
    }
}